apiVersion: v1
kind: Service
metadata:
  name: flower
  namespace: airflow
spec:
  type: NodePort
  selector:
    app: airflow
    tier: flower
  ports:
    - name: flower
      protocol: TCP
      port: 5555
      targetPort: flower
      nodePort: 32081