apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flower
  namespace: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: flower
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: preemptible-pool
      restartPolicy: Always
      containers:
        - name: flower
          image: gcr.io/sqhive-backend/airflow:latest
          imagePullPolicy: Always
          args: [ "flower" ]
          env:
            - name: AIRFLOW_HOME
              value: "/usr/local/airflow"
            - name: FLOWER_PORT
              value: "5555"
          volumeMounts:
            - mountPath: /usr/local/airflow/dags
              name: airflow-dags
            - mountPath: /usr/local/airflow/logs
              name: airflow-logs
          ports:
            - name: flower
              containerPort: 5555
      volumes:
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: nfs-airflow-dags
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: nfs-airflow-logs