apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: airflow
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: postgres