apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scheduler
  namespace: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: scheduler
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: preemptible-pool
      restartPolicy: Always
      containers:
        - name: scheduler
          image: gcr.io/sqhive-backend/airflow:latest
          env:
            - name: AIRFLOW_HOME
              value: "/usr/local/airflow"
          args: [ "scheduler", "-n", "5" ]
          volumeMounts:
            - mountPath: /usr/local/airflow/dags
              name: airflow-dags
      volumes:
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: nfs-airflow-dags