apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: airflow
spec:
  type: NodePort
  selector:
    app: airflow
    tier: web
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
      nodePort: 32080