apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: web
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: preemptible-pool
      restartPolicy: Always
      containers:
        - name: web
          image: gcr.io/sqhive-backend/airflow:latest
          args: [ "webserver" ]
          env:
          - name: AIRFLOW_HOME
            value: "/usr/local/airflow"
          ports:
          - name: web
            containerPort: 8080
          volumeMounts:
            - mountPath: /usr/local/airflow/dags
              name: airflow-dags
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 240
            periodSeconds: 60
      volumes:
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: nfs-airflow-dags