apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: worker
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: preemptible-pool
      restartPolicy: Always
      containers:
        - name: worker
          image: mumoshu/kube-airflow:1.8.0.0-1.6.1
          env:
            - name: AIRFLOW_HOME
              value: "/usr/local/airflow"
          args: ["worker"]
          volumeMounts:
            - mountPath: /usr/local/airflow/dags
              name: airflow-dags
      volumes:
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: nfs-airflow-dags